### ISSUE TITLE
Add a cod of conduct to all of our repositories

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-common#258]
After dealing with a few incidents, it's become clear that we need a code of conduct in each our repositories. We should use the one here:
https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/CODE_OF_CONDUCT.md

Ideally, this is something @dpebot could do for us :) @jmdobry @theacodes @broady

**Comment by jskeet** [comment]
Done for the main .NET repo, but we have a few others (which are much less publicly used).

**Comment by jdpedrie** [comment]
[google-cloud-php](https://github.com/GoogleCloudPlatform/google-cloud-php) has a CoC. Our subrepos (i.e. [google-cloud-php-datastore](https://github.com/GoogleCloudPlatform/google-cloud-php-datastore)) do not, but they do not accept contributions and any issues or Pull Requests are directed to the main repository, so I don't think they are necessary. If the consensus believes otherwise, we'll get them added across the board.

**Comment by theacodes** [comment]
I'll handle this across all repos today or tomorrow.

**Comment by JustinBeckwith** [comment]
# COD OF CONDUCT

![image](https://user-images.githubusercontent.com/534619/42174989-e712b6b4-7dd8-11e8-89b4-8c44949d8429.png)

**Comment by blowmage** [comment]
Ruby has a CoC:
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/CODE_OF_CONDUCT.md

We have discussed this previously here:

https://github.com/GoogleCloudPlatform/gcloud-common-private/issues/18
https://github.com/GoogleCloudPlatform/google-cloud-common/pull/23

**Comment by theacodes** [comment]
This is done, with one tiny tweak: I added a *code* of conduct. I couldn't find enough fish to add *cod*s to every repo.

**Comment by JustinBeckwith** [comment]
@theacodes if you can find that many sink gifs, I think you can find enough cods.

**Comment by iantalarico** [comment]
I just did this for all .NET repos the C# Tools team owns
